print('----------------------------' * 4)
print('\t\t\t\t\tSOME OPRATORS AND THEIR NAMES')
print('----------------------------' * 4)
print('\nS/N \tOPERATOR \t\t\tNAMES')
print('\n1 \t"+=" \t\t\t\tIncrement By')
print('2 \t"-=" \t\t\t\tDecrement By')
print('3 \t"/=" \t\t\t\tDivide By')
print('4 \t"*=" \t\t\t\tMultiply By')
print('5 \t"%" \t\t\t\tModulo')
print('6 \t"//" \t\t\t\tFloor or Raminder')
print('7 \t"|" \t\t\t\tBitwise OR')
print('8 \t"&" \t\t\t\tBitwise XOR')
print('9 \t"<<", ">>" \t\t\tShifts')
print('10 \t"@" \t\t\t\tMatrix multiplication')
print('11 \t"+x", "-x", "~x" \t\tPositive, Negative, Bitwise NOT')
print('12 \t"**" \t\t\t\tExponentiation')